#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.

host = data.get("host")
URL_HOST = f"https://{host}"

# KEILA_USER		root@localhost	Email address for the root user
# KEILA_PASSWORD
KEILA_USER = data.get("KEILA_USER", "admin@admin.com")
KEILA_PASSWORD = data.get("KEILA_PASSWORD", "admin")

# Email configuration
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

SMTP_HOST = smtp_settings['host']
SMTP_PORT = smtp_settings['port']
SMTP_USERNAME = smtp_settings['username']
SMTP_PASSWORD = smtp_settings['password']
SMTP_ENCRYPTION = smtp_settings['encrypt_smtp']
SMTP_TLSVERIFY = smtp_settings['tls_verify']

keila = {
    "URL_HOST": URL_HOST,
    "KEILA_USER": KEILA_USER,
    "KEILA_PASSWORD": KEILA_PASSWORD,
    "MAILER_SMTP_HOST": SMTP_HOST,
    "MAILER_SMTP_PORT": SMTP_PORT,
    "MAILER_SMTP_USER": SMTP_USERNAME,
    "MAILER_SMTP_PASSWORD": SMTP_PASSWORD,
    "MAILER_SMTP_FROM_EMAIL": SMTP_USERNAME,
    "MAILER_ENABLE_SSL": 'true' if SMTP_ENCRYPTION == 'ssl' else 'false',
    "MAILER_ENABLE_STARTTLS": 'true' if SMTP_TLSVERIFY == 'tls' else 'false'
}
agent.write_envfile("keila.env", keila)
#agent.dump_env()
